// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/environment.proto

package lsfn

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JoinServer struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinServer) Reset()         { *m = JoinServer{} }
func (m *JoinServer) String() string { return proto.CompactTextString(m) }
func (*JoinServer) ProtoMessage()    {}
func (*JoinServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_5453b116d733dfde, []int{0}
}

func (m *JoinServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinServer.Unmarshal(m, b)
}
func (m *JoinServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinServer.Marshal(b, m, deterministic)
}
func (m *JoinServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinServer.Merge(m, src)
}
func (m *JoinServer) XXX_Size() int {
	return xxx_messageInfo_JoinServer.Size(m)
}
func (m *JoinServer) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinServer.DiscardUnknown(m)
}

var xxx_messageInfo_JoinServer proto.InternalMessageInfo

type Welcome struct {
	Ship                 *ShipDescription `protobuf:"bytes,1,opt,name=ship,proto3" json:"ship,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Welcome) Reset()         { *m = Welcome{} }
func (m *Welcome) String() string { return proto.CompactTextString(m) }
func (*Welcome) ProtoMessage()    {}
func (*Welcome) Descriptor() ([]byte, []int) {
	return fileDescriptor_5453b116d733dfde, []int{1}
}

func (m *Welcome) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Welcome.Unmarshal(m, b)
}
func (m *Welcome) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Welcome.Marshal(b, m, deterministic)
}
func (m *Welcome) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Welcome.Merge(m, src)
}
func (m *Welcome) XXX_Size() int {
	return xxx_messageInfo_Welcome.Size(m)
}
func (m *Welcome) XXX_DiscardUnknown() {
	xxx_messageInfo_Welcome.DiscardUnknown(m)
}

var xxx_messageInfo_Welcome proto.InternalMessageInfo

func (m *Welcome) GetShip() *ShipDescription {
	if m != nil {
		return m.Ship
	}
	return nil
}

func init() {
	proto.RegisterType((*JoinServer)(nil), "lsfn.JoinServer")
	proto.RegisterType((*Welcome)(nil), "lsfn.Welcome")
}

func init() { proto.RegisterFile("api/proto/environment.proto", fileDescriptor_5453b116d733dfde) }

var fileDescriptor_5453b116d733dfde = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4e, 0x2c, 0xc8, 0xd4,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0xcd, 0x2b, 0xcb, 0x2c, 0xca, 0xcf, 0xcb, 0x4d, 0xcd,
	0x2b, 0xd1, 0x03, 0x8b, 0x08, 0xb1, 0xe4, 0x14, 0xa7, 0xe5, 0x49, 0x89, 0x20, 0x94, 0x14, 0x67,
	0x64, 0x16, 0x40, 0xe4, 0x94, 0x78, 0xb8, 0xb8, 0xbc, 0xf2, 0x33, 0xf3, 0x82, 0x53, 0x8b, 0xca,
	0x52, 0x8b, 0x94, 0x4c, 0xb8, 0xd8, 0xc3, 0x53, 0x73, 0x92, 0xf3, 0x73, 0x53, 0x85, 0x34, 0xb9,
	0x58, 0x40, 0xca, 0x24, 0x18, 0x15, 0x18, 0x35, 0xb8, 0x8d, 0x44, 0xf5, 0x40, 0x66, 0xe8, 0x05,
	0x67, 0x64, 0x16, 0xb8, 0xa4, 0x16, 0x27, 0x17, 0x65, 0x16, 0x94, 0x64, 0xe6, 0xe7, 0x05, 0x81,
	0x95, 0x18, 0x19, 0x71, 0xb1, 0xfa, 0xe4, 0x27, 0x25, 0x55, 0x82, 0xf4, 0x80, 0x0c, 0x13, 0x12,
	0x80, 0xa8, 0x46, 0x18, 0x2c, 0xc5, 0x0b, 0x11, 0x81, 0x1a, 0xae, 0xc4, 0x90, 0xc4, 0x06, 0xb6,
	0xde, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x50, 0x0b, 0x80, 0x38, 0xb9, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LobbyClient is the client API for Lobby service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LobbyClient interface {
	Join(ctx context.Context, in *JoinServer, opts ...grpc.CallOption) (*Welcome, error)
}

type lobbyClient struct {
	cc *grpc.ClientConn
}

func NewLobbyClient(cc *grpc.ClientConn) LobbyClient {
	return &lobbyClient{cc}
}

func (c *lobbyClient) Join(ctx context.Context, in *JoinServer, opts ...grpc.CallOption) (*Welcome, error) {
	out := new(Welcome)
	err := c.cc.Invoke(ctx, "/lsfn.Lobby/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LobbyServer is the server API for Lobby service.
type LobbyServer interface {
	Join(context.Context, *JoinServer) (*Welcome, error)
}

func RegisterLobbyServer(s *grpc.Server, srv LobbyServer) {
	s.RegisterService(&_Lobby_serviceDesc, srv)
}

func _Lobby_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinServer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LobbyServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lsfn.Lobby/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LobbyServer).Join(ctx, req.(*JoinServer))
	}
	return interceptor(ctx, in, info, handler)
}

var _Lobby_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lsfn.Lobby",
	HandlerType: (*LobbyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _Lobby_Join_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/environment.proto",
}
