// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/ship.proto

package lsfn

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShipUpdate struct {
	// Types that are valid to be assigned to Union:
	//	*ShipUpdate_Control
	//	*ShipUpdate_Sensor
	Union                isShipUpdate_Union `protobuf_oneof:"Union"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ShipUpdate) Reset()         { *m = ShipUpdate{} }
func (m *ShipUpdate) String() string { return proto.CompactTextString(m) }
func (*ShipUpdate) ProtoMessage()    {}
func (*ShipUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaf99ebe527c4502, []int{0}
}

func (m *ShipUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShipUpdate.Unmarshal(m, b)
}
func (m *ShipUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShipUpdate.Marshal(b, m, deterministic)
}
func (m *ShipUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShipUpdate.Merge(m, src)
}
func (m *ShipUpdate) XXX_Size() int {
	return xxx_messageInfo_ShipUpdate.Size(m)
}
func (m *ShipUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ShipUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ShipUpdate proto.InternalMessageInfo

type isShipUpdate_Union interface {
	isShipUpdate_Union()
}

type ShipUpdate_Control struct {
	Control *ControlState `protobuf:"bytes,1,opt,name=control,proto3,oneof"`
}

type ShipUpdate_Sensor struct {
	Sensor *SensorState `protobuf:"bytes,2,opt,name=sensor,proto3,oneof"`
}

func (*ShipUpdate_Control) isShipUpdate_Union() {}

func (*ShipUpdate_Sensor) isShipUpdate_Union() {}

func (m *ShipUpdate) GetUnion() isShipUpdate_Union {
	if m != nil {
		return m.Union
	}
	return nil
}

func (m *ShipUpdate) GetControl() *ControlState {
	if x, ok := m.GetUnion().(*ShipUpdate_Control); ok {
		return x.Control
	}
	return nil
}

func (m *ShipUpdate) GetSensor() *SensorState {
	if x, ok := m.GetUnion().(*ShipUpdate_Sensor); ok {
		return x.Sensor
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ShipUpdate) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ShipUpdate_Control)(nil),
		(*ShipUpdate_Sensor)(nil),
	}
}

type ShipCommand struct {
	Control              *ChangeControl `protobuf:"bytes,1,opt,name=control,proto3" json:"control,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ShipCommand) Reset()         { *m = ShipCommand{} }
func (m *ShipCommand) String() string { return proto.CompactTextString(m) }
func (*ShipCommand) ProtoMessage()    {}
func (*ShipCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaf99ebe527c4502, []int{1}
}

func (m *ShipCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShipCommand.Unmarshal(m, b)
}
func (m *ShipCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShipCommand.Marshal(b, m, deterministic)
}
func (m *ShipCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShipCommand.Merge(m, src)
}
func (m *ShipCommand) XXX_Size() int {
	return xxx_messageInfo_ShipCommand.Size(m)
}
func (m *ShipCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ShipCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ShipCommand proto.InternalMessageInfo

func (m *ShipCommand) GetControl() *ChangeControl {
	if m != nil {
		return m.Control
	}
	return nil
}

type ShipDescription struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Controls             []*ControlDescription `protobuf:"bytes,3,rep,name=controls,proto3" json:"controls,omitempty"`
	Sensors              []*SensorDescription  `protobuf:"bytes,4,rep,name=sensors,proto3" json:"sensors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ShipDescription) Reset()         { *m = ShipDescription{} }
func (m *ShipDescription) String() string { return proto.CompactTextString(m) }
func (*ShipDescription) ProtoMessage()    {}
func (*ShipDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaf99ebe527c4502, []int{2}
}

func (m *ShipDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShipDescription.Unmarshal(m, b)
}
func (m *ShipDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShipDescription.Marshal(b, m, deterministic)
}
func (m *ShipDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShipDescription.Merge(m, src)
}
func (m *ShipDescription) XXX_Size() int {
	return xxx_messageInfo_ShipDescription.Size(m)
}
func (m *ShipDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_ShipDescription.DiscardUnknown(m)
}

var xxx_messageInfo_ShipDescription proto.InternalMessageInfo

func (m *ShipDescription) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ShipDescription) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ShipDescription) GetControls() []*ControlDescription {
	if m != nil {
		return m.Controls
	}
	return nil
}

func (m *ShipDescription) GetSensors() []*SensorDescription {
	if m != nil {
		return m.Sensors
	}
	return nil
}

func init() {
	proto.RegisterType((*ShipUpdate)(nil), "lsfn.ShipUpdate")
	proto.RegisterType((*ShipCommand)(nil), "lsfn.ShipCommand")
	proto.RegisterType((*ShipDescription)(nil), "lsfn.ShipDescription")
}

func init() { proto.RegisterFile("api/proto/ship.proto", fileDescriptor_eaf99ebe527c4502) }

var fileDescriptor_eaf99ebe527c4502 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4e, 0xc3, 0x30,
	0x10, 0x44, 0x69, 0x1a, 0x1a, 0xba, 0x91, 0x40, 0x2c, 0x88, 0x5a, 0x3d, 0x55, 0x39, 0x55, 0x42,
	0xa4, 0xa2, 0x70, 0xe4, 0x44, 0x39, 0x70, 0x4e, 0xd4, 0x0f, 0x30, 0x8d, 0x21, 0x96, 0x9a, 0xb5,
	0x65, 0xfb, 0x7b, 0xf8, 0x56, 0x14, 0xdb, 0x29, 0x81, 0x9b, 0x35, 0xfb, 0x66, 0x66, 0xd7, 0x70,
	0xcb, 0xb5, 0xdc, 0x68, 0xa3, 0x9c, 0xda, 0xd8, 0x56, 0xea, 0xd2, 0x3f, 0x31, 0x3d, 0xda, 0x4f,
	0x5a, 0x2e, 0x7e, 0x67, 0x07, 0x45, 0xce, 0xa8, 0x63, 0x18, 0x2f, 0xef, 0x46, 0x26, 0x41, 0x56,
	0x99, 0xa0, 0x17, 0x06, 0xa0, 0x6e, 0xa5, 0xde, 0xeb, 0x86, 0x3b, 0x81, 0x25, 0x64, 0xd1, 0xc6,
	0x26, 0xab, 0xc9, 0x3a, 0xdf, 0x62, 0xd9, 0xc7, 0x96, 0xbb, 0x20, 0xd6, 0x8e, 0x3b, 0xf1, 0x7e,
	0x56, 0x0d, 0x10, 0xde, 0xc3, 0x2c, 0xa4, 0xb1, 0xc4, 0xe3, 0xd7, 0x01, 0xaf, 0xbd, 0x36, 0xd0,
	0x11, 0x79, 0xcd, 0xe0, 0x7c, 0x4f, 0x52, 0x51, 0xf1, 0x02, 0x79, 0xdf, 0xb9, 0x53, 0x5d, 0xc7,
	0xa9, 0xc1, 0x87, 0xff, 0xa5, 0x37, 0xb1, 0xb4, 0xe5, 0xf4, 0x25, 0x62, 0xf5, 0xa9, 0xb3, 0xf8,
	0x9e, 0xc0, 0x55, 0x6f, 0x7f, 0x13, 0xf6, 0x60, 0xa4, 0x76, 0x52, 0x11, 0x5e, 0x42, 0x22, 0x1b,
	0xef, 0x9e, 0x57, 0x89, 0x6c, 0x10, 0x21, 0x25, 0xde, 0x09, 0xbf, 0xd5, 0xbc, 0xf2, 0x6f, 0x7c,
	0x86, 0x8b, 0x18, 0x61, 0xd9, 0x74, 0x35, 0x5d, 0xe7, 0x5b, 0xf6, 0xe7, 0xb8, 0x51, 0x5e, 0x75,
	0x22, 0xf1, 0x11, 0xb2, 0xb0, 0xbe, 0x65, 0xa9, 0x37, 0x2d, 0xc6, 0x27, 0x8e, 0x3d, 0x03, 0xf7,
	0x31, 0xf3, 0x3f, 0xfb, 0xf4, 0x13, 0x00, 0x00, 0xff, 0xff, 0x4e, 0xe8, 0x35, 0x3c, 0xa8, 0x01,
	0x00, 0x00,
}
