// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/ship.proto

package lsfn

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShipDescription struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Controls             []*ControlDescription `protobuf:"bytes,3,rep,name=controls,proto3" json:"controls,omitempty"`
	Sensors              []*SensorDescription  `protobuf:"bytes,4,rep,name=sensors,proto3" json:"sensors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ShipDescription) Reset()         { *m = ShipDescription{} }
func (m *ShipDescription) String() string { return proto.CompactTextString(m) }
func (*ShipDescription) ProtoMessage()    {}
func (*ShipDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaf99ebe527c4502, []int{0}
}

func (m *ShipDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShipDescription.Unmarshal(m, b)
}
func (m *ShipDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShipDescription.Marshal(b, m, deterministic)
}
func (m *ShipDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShipDescription.Merge(m, src)
}
func (m *ShipDescription) XXX_Size() int {
	return xxx_messageInfo_ShipDescription.Size(m)
}
func (m *ShipDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_ShipDescription.DiscardUnknown(m)
}

var xxx_messageInfo_ShipDescription proto.InternalMessageInfo

func (m *ShipDescription) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ShipDescription) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ShipDescription) GetControls() []*ControlDescription {
	if m != nil {
		return m.Controls
	}
	return nil
}

func (m *ShipDescription) GetSensors() []*SensorDescription {
	if m != nil {
		return m.Sensors
	}
	return nil
}

func init() {
	proto.RegisterType((*ShipDescription)(nil), "lsfn.ShipDescription")
}

func init() { proto.RegisterFile("api/proto/ship.proto", fileDescriptor_eaf99ebe527c4502) }

var fileDescriptor_eaf99ebe527c4502 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0x2c, 0xc8, 0xd4,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f, 0xce, 0xc8, 0x2c, 0xd0, 0x03, 0x33, 0x85, 0x58, 0x72,
	0x8a, 0xd3, 0xf2, 0xa4, 0xc4, 0x11, 0x72, 0xc9, 0xf9, 0x79, 0x25, 0x45, 0xf9, 0x39, 0x10, 0x69,
	0x29, 0x31, 0x24, 0x4d, 0xa9, 0x79, 0xc5, 0xf9, 0x45, 0x10, 0x71, 0xa5, 0x79, 0x8c, 0x5c, 0xfc,
	0xc1, 0x19, 0x99, 0x05, 0x2e, 0xa9, 0xc5, 0xc9, 0x45, 0x99, 0x05, 0x25, 0x99, 0xf9, 0x79, 0x42,
	0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x4c, 0x99, 0x29, 0x42,
	0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x60, 0x11, 0x30, 0x5b, 0xc8, 0x84, 0x8b,
	0x03, 0x6a, 0x41, 0xb1, 0x04, 0xb3, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0x84, 0x1e, 0xc8, 0x05, 0x7a,
	0xce, 0x10, 0x51, 0x24, 0xf3, 0x82, 0xe0, 0x2a, 0x85, 0x0c, 0xb9, 0xd8, 0x21, 0xb6, 0x17, 0x4b,
	0xb0, 0x80, 0x35, 0x89, 0x43, 0x34, 0x05, 0x83, 0x05, 0x91, 0xf5, 0xc0, 0xd4, 0x25, 0xb1, 0x81,
	0xdd, 0x69, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x45, 0xb6, 0xc1, 0xfe, 0xf6, 0x00, 0x00, 0x00,
}
