[package]
name = "vessel"
version = "0.1.0"
authors = ["James Laverack <james@jameslaverack.com>"]

[dependencies]
glium = "*"
glium_text = "*"
cgmath = "*"
gl = "*"
prost = "0.3.0"
prost-derive = "0.3.0"
prost-types = "0.3.0"
bytes = "0.4.6"

[build-dependencies]
prost-build = "0.3.0"
